// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package database

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT email, password FROM account WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, email)
	var i Account
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const registerAccount = `-- name: RegisterAccount :one
INSERT INTO account(email, password)
VALUES(
    $1,
    $2
)
RETURNING email, password
`

type RegisterAccountParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) RegisterAccount(ctx context.Context, arg RegisterAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, registerAccount, arg.Email, arg.Password)
	var i Account
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}
