// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Flashcard struct {
	ID    uuid.NullUUID
	Front sql.NullString
	Back  sql.NullString
}
