// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type Flashcard struct {
	ID    uuid.UUID `json:"id"`
	Front string    `json:"front"`
	Back  string    `json:"back"`
}
