// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (id, title, description, email)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, title, description, email
`

type CreateSetParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Email       string    `json:"email"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRowContext(ctx, createSet,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Email,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Email,
	)
	return i, err
}
